# Generated by Django 5.2.17 on 2026-08-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_brand_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بخش')),
                ('type', models.CharField(choices=[('banners', 'بنرها'), ('categories', 'دسته\u200cبندی\u200cها'), ('flash_sale', 'پیشنهاد شگفت\u200cانگیز'), ('brands', 'برندها'), ('bestsellers', 'پرفروش\u200cترین\u200cها'), ('most_discounted', 'بیشترین تخفیف'), ('least_sellers', 'کم\u200cفروش\u200cترین\u200cها'), ('newest', 'جدیدترین\u200cها'), ('discounted', 'محصولات تخفیف\u200cدار'), ('manual', 'انتخاب دستی')], max_length=20, verbose_name='نوع بخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('auto_mode', models.BooleanField(default=True, verbose_name='انتخاب خودکار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionManualProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_homepage_sections', to='products.product', verbose_name='محصول')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_products', to='admin_homepage.homepagesection', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'محصول دستی بخش',
                'verbose_name_plural': 'محصولات دستی بخش',
                'ordering': ['order'],
                'unique_together': {('section', 'product')},
            },
        ),
    ]
