# Generated by Django 5.2.12 on 2026-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='banners/', verbose_name='فایل بنر دسکتاپ')),
                ('mobile_file', models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='فایل بنر موبایل (اختیاری)')),
                ('banner_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=10, verbose_name='نوع')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='لینک مقصد')),
                ('new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('scheduled', 'زمان\u200cبندی شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70, verbose_name='عنوان سئو')),
                ('seo_description', models.TextField(blank=True, default='', max_length=160, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
