# Generated by Django 5.2.16 on 2026-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg_raw',
            field=models.TextField(blank=True, default='', verbose_name='محتوای خام SVG'),
        ),
    ]
