# Generated by Django 5.2.12 on 2026-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_add_slug_with_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='لینک'),
        ),
    ]
