# Generated by Django 5.2.12 on 2026-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('role', models.CharField(choices=[('admin', 'مدیر کل'), ('manager', 'مدیر'), ('editor', 'ویرایشگر'), ('customer', 'مشتری')], default='customer', max_length=20, verbose_name='نقش')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('banned', 'مسدود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('orders_count', models.IntegerField(default=0, verbose_name='تعداد سفارشات')),
                ('total_spent', models.BigIntegerField(default=0, verbose_name='مجموع خرید')),
            ],
        ),
    ]
