# Generated by Django 5.2.16 on 2026-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_file',
            field=models.FileField(blank=True, null=True, upload_to='banners/', verbose_name='فایل بنر موبایل (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='file',
            field=models.FileField(upload_to='banners/', verbose_name='فایل بنر دسکتاپ'),
        ),
    ]
