# Generated by Django 5.2.16 on 2026-08-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_created_at_alter_brand_logo_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand', verbose_name='برند'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
